apiVersion: build.openshift.io/v1
kind: "BuildConfig"
metadata:
  name: "appdev-homework-grading"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/wkulhanek/advdev_homework_grading"
  strategy:
    jenkinsPipelineStrategy:
      env:
        - name: GUID
          value: wkha
        - name: CLUSTER
          value: na39.openshift.opentlc.com
        - name: REPO
          value: 'https://github.com/wkulhanek/advdev_homework_template'
        - name: SETUP
          value: 'True'
        - name: DELETE
          value: 'False'
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline