apiVersion: v1
kind: List
metadata: []
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "appdev-homework-grading"
  spec:
    source:
      type: "Git"
      git:
        uri: "https://github.com/wkulhanek/advdev_homework_grading"
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
